[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "luxai-magpie"
description = "MAGPIE is a lightweight, modular messaging engine providing high-performance pub/sub and RPC over pluggable transports."
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [
    { name = "LuxAI S.A." }
]
keywords = ["messaging", "rpc", "pubsub", "zeromq", "distributed-systems", "robotics", "middleware"]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Distributed Computing",
    "Topic :: System :: Networking",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Video",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
]
# Important: version is dynamic
dynamic = ["version"]

dependencies = [
    "typing_extensions",
    "python-ulid",
    "msgpack",
    "pyzmq",
]

[project.optional-dependencies]
video = [
    "numpy",
    "simplejpeg",
    "opencv-python",
]
audio = [
    "numpy",
    "soundfile",
    "sounddevice",
]

mqtt = [
    "paho-mqtt>=1.6.0",
]

discovery = [
    "zeroconf",
]

webrtc = [
    "aiortc>=1.6.0",
    "numpy",
]

dev = [
    "numpy",
    "opencv-python",
    "simplejpeg",
    "sounddevice",
    "soundfile",
    "zeroconf",
    "paho-mqtt>=1.6.0",
    "aiortc>=1.6.0",
    "pytest",
    "coverage",
]

full = [
    "numpy",
    "opencv-python",
    "simplejpeg",
    "sounddevice",
    "soundfile",
    "zeroconf",
    "paho-mqtt>=1.6.0",
    "aiortc>=1.6.0",
]


[project.urls]
"Homepage" = "https://github.com/luxai-qtrobot/magpie"
"Source" = "https://github.com/luxai-qtrobot/magpie"
"Bug Tracker" = "https://github.com/luxai-qtrobot/magpie/issues"


[project.scripts]
magpie-audio-player = "luxai.magpie.tools.zmq_audio_player:main"
magpie-audio-capture = "luxai.magpie.tools.zmq_audio_capture:main"
magpie-video-viewer = "luxai.magpie.tools.zmq_video_viewer:main"
magpie-video-capture = "luxai.magpie.tools.zmq_video_capture:main"
magpie-request = "luxai.magpie.tools.zmq_request:main"
magpie-subscribe = "luxai.magpie.tools.zmq_subscribe:main"
magpie-publish = "luxai.magpie.tools.zmq_publish:main"
magpie-discovery = "luxai.magpie.tools.zconf_discovery:main"
magpie-publish-mqtt = "luxai.magpie.tools.mqtt_publish:main"
magpie-subscribe-mqtt = "luxai.magpie.tools.mqtt_subscribe:main"
magpie-request-mqtt = "luxai.magpie.tools.mqtt_request:main"
magpie-publish-webrtc = "luxai.magpie.tools.webrtc_publish:main"
magpie-subscribe-webrtc = "luxai.magpie.tools.webrtc_subscribe:main"
magpie-request-webrtc = "luxai.magpie.tools.webrtc_request:main"
magpie-video-capture-webrtc = "luxai.magpie.tools.webrtc_video_capture:main"
magpie-video-viewer-webrtc = "luxai.magpie.tools.webrtc_video_viewer:main"
magpie-audio-capture-webrtc = "luxai.magpie.tools.webrtc_audio_capture:main"
magpie-audio-player-webrtc = "luxai.magpie.tools.webrtc_audio_player:main"

# -----------------------------
# setuptools configuration
# -----------------------------
[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["luxai.magpie*"]

[tool.setuptools.package-data]
"luxai.magpie" = ["assets/*.png"]

# This tells setuptools how to read version dynamically
[tool.setuptools.dynamic]
version = {attr = "luxai.magpie.__version__"}
